import type { TenantMetricsData } from "@/features/metrics/metrics-types";

export const LOCKED_METRICS_PREVIEW_DATA: TenantMetricsData = {
  series: [
    {
      periodStart: "2026-05-18",
      periodEnd: "2026-05-18",
      bookingsCount: 18,
      completedCount: 15,
      noShowCount: 1,
      cancelledCount: 2,
      revenueCompleted: 640000,
      bookedMinutes: 720,
      capacityMinutes: 960,
      occupancyRate: 0.75,
      isToday: false,
      isLive: false,
    },
    {
      periodStart: "2026-05-19",
      periodEnd: "2026-05-19",
      bookingsCount: 24,
      completedCount: 21,
      noShowCount: 1,
      cancelledCount: 2,
      revenueCompleted: 890000,
      bookedMinutes: 840,
      capacityMinutes: 960,
      occupancyRate: 0.875,
      isToday: false,
      isLive: false,
    },
    {
      periodStart: "2026-05-20",
      periodEnd: "2026-05-20",
      bookingsCount: 21,
      completedCount: 17,
      noShowCount: 2,
      cancelledCount: 2,
      revenueCompleted: 720000,
      bookedMinutes: 660,
      capacityMinutes: 960,
      occupancyRate: 0.6875,
      isToday: false,
      isLive: false,
    },
    {
      periodStart: "2026-05-21",
      periodEnd: "2026-05-21",
      bookingsCount: 28,
      completedCount: 24,
      noShowCount: 1,
      cancelledCount: 3,
      revenueCompleted: 1030000,
      bookedMinutes: 900,
      capacityMinutes: 960,
      occupancyRate: 0.9375,
      isToday: false,
      isLive: false,
    },
    {
      periodStart: "2026-05-22",
      periodEnd: "2026-05-22",
      bookingsCount: 16,
      completedCount: 12,
      noShowCount: 1,
      cancelledCount: 1,
      revenueCompleted: 510000,
      bookedMinutes: 480,
      capacityMinutes: 960,
      occupancyRate: 0.5,
      isToday: true,
      isLive: true,
    },
  ],
  totals: {
    bookingsCount: 107,
    completedCount: 89,
    noShowCount: 6,
    cancelledCount: 10,
    completionRate: 0.832,
    noShowRate: 0.056,
    cancellationRate: 0.093,
    revenueCompleted: 3790000,
    averageOccupancyRate: 0.75,
    daysWithKnownCapacity: 5,
    daysWithNullCapacity: 0,
  },
  topServices: [
    { serviceId: "preview-service-1", bookingsCount: 42, revenueCompleted: 1680000 },
    { serviceId: "preview-service-2", bookingsCount: 28, revenueCompleted: 980000 },
    { serviceId: "preview-service-3", bookingsCount: 16, revenueCompleted: 540000 },
  ],
  topResources: [
    {
      resourceId: "preview-resource-1",
      resourceType: "PROFESSIONAL",
      bookingsCount: 38,
      completedCount: 33,
      revenueCompleted: 1420000,
      occupancyRate: 0.81,
    },
    {
      resourceId: "preview-resource-2",
      resourceType: "PROFESSIONAL",
      bookingsCount: 31,
      completedCount: 27,
      revenueCompleted: 1210000,
      occupancyRate: 0.74,
    },
  ],
  topClients: [
    { clientId: "preview-client-1", visitsCount: 8, revenue: 320000 },
    { clientId: "preview-client-2", visitsCount: 6, revenue: 260000 },
  ],
  meta: {
    from: "2026-05-18",
    to: "2026-05-22",
    granularity: "day",
    timezone: "America/Asuncion",
    currency: "PYG",
    revenueBasis: "COMPLETED_ONLY",
    includesToday: true,
    todayIsLive: true,
  },
};
